apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nagapavani2301/backend:latest
        env:
        - name: SQLITE_DB_PATH
          value: "/app/data/tasksdb.db"   # path to SQLite DB file
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: sqlite-storage
          mountPath: /app/data   # folder where DB file will live
      volumes:
      - name: sqlite-storage
        emptyDir: {}   # temp storage (will reset if pod restarts)
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
