apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: 20.3.38.117.nip.io
    http:
      paths:
      # Match /api, /api/ and anything under /api/*
      - path: /api(/.*)?
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 80
      # Everything else goes to frontend
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
